
danger_scores = {
    "Homicide - Criminal": 5,
    "Robbery Firearm": 5,
    "Aggravated Assault Firearm": 5,
    "Rape": 5,
    "Aggravated Assault No Firearm": 4,
    "Robbery No Firearm": 4,
    "Burglary Residential": 4,
    "Burglary Non-Residential": 3,
    "Motor Vehicle Theft": 3,
    "Thefts": 2,
    "Theft from Vehicle": 2,
    "Receiving Stolen Property": 2,
    "Fraud": 1,
    "Embezzlement": 1,
    "Forgery and Counterfeiting": 1,
    "Vandalism/Criminal Mischief": 1,
    "Narcotic / Drug Law Violations": 2,
    "Weapon Violations": 3,
    "Offenses Against Family and Children": 4,
    "Public Drunkenness": 2,
    "Disorderly Conduct": 2,
    "Prostitution and Commercialized Vice": 2,
    "Other Sex Offenses (Not Commercialized)": 3,
    "Arson": 5,
    "Liquor Law Violations": 1,
    "DRIVING UNDER THE INFLUENCE": 3,
    "Vagrancy/Loitering": 1,
    "Gambling Violations": 1,
    "Other Assaults": 3
}